version: "3"

services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password

      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./.data/database-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/src:/var/www/html/api
      - ./backend/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.cert/mycert.crt:/etc/ssl/certs/ssl_cert.crt
      # - ./.cert/mycert.key:/etc/ssl/private/ssl_cert.key
      - /etc/letsencrypt/live/kpopfiesta.live/fullchain.pem:/etc/ssl/certs/ssl_cert.crt
      - /etc/letsencrypt/live/kpopfiesta.live/privkey.pem:/etc/ssl/private/ssl_cert.key
    depends_on:
      - database

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - DEBUG=${DEBUG}
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend
    # volumes:
    # - ./frontend:/app
