version: "3"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret

      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./.data/database-data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
      - database
